workspace:
  base: /workspace
  path: poc

pipeline:
  build_mrp_image:
    image: plugins/docker
    repo: harmeetg/mrp
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    secrets: [ docker_username, docker_password ]
    dockerfile: mrp/dockerfile
    context: mrp
    tag: ${DRONE_COMMIT}
    pull_image: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  publish_mrp:
    image: docker
    commands:
      - docker stop cntr_mrp
      - docker run --rm --pull=true -d --name cntr_mrp 0.0.0.0:80:4000 -d docker.io/harmeetg/mrp:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      environment: dev

  publish_mrp_to_gcr:
    image: nytimes/drone-gke
    cluster: drone-demo
    zone: us-central1-a
    namespace: ${DRONE_BRANCH}
    template: mrp/.kube.yml
    secret_template: mrp/.kube.sec.yml
    environment:
      - USER=root
    expand_env_vars: true
    vars:
      image: docker.io/harmeetg/mrp:${DRONE_COMMIT}
      app: mrp
      env: prod
      user: $${USER}
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: token
      - source: SAMPLE_SECRET_1
        target: secret_api_token
      - source: SAMPLE_SECRET_64
        target: secret_base64_p12_cert
        



