workspace:
  base: /workspace
  path: poc

pipeline:
  build_mrp_image:
    image: plugins/docker
    repo: harmeetg/mrp
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    secrets: [ docker_username, docker_password ]
    dockerfile: mrp/dockerfile
    context: mrp
    pull: false
    when:
      environment: drone
  
  publish_mrp:
    image: docker
    commands:
      - docker run --rm -d -p 0.0.0.0:80:4000 harmeetg/mrp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      environment: dev

  publish_mrp_to_gcr:
    image: plugins/gcr
    registry: docker.io
    tags: latest
    repo: harmeetg/mrp
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    secrets: [ docker_username, docker_password, gcr_json_key_base64 ]
    dockerfile: mrp/dockerfile
    context: mrp
    pull: false
    json_key: ${GCR_JSON_KEY_BASE64}
    when:
      event: deployment
      environment: prod



