workspace:
  base: /workspace
  path: poc

pipeline:
  build_mrp_image:
    image: plugins/docker
    repo: harmeetg/mrp
    username: ${docker_username}
    password: ${docker_password}
    dockerfile: mrp/dockerfile
    context: mrp
    pull: false
  
  publish_mrp:
    image: docker
    commands:
      - docker run --rm -d -p 0.0.0.0:80:4000 harmeetg/mrp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: deployment
      environment: dev

  publish_mrp_to_gcr:
    image: plugins/gcr
    registry: hub.docker.com
    repo: harmeetg/mrp
    tags: latest
    json_key: ${gcr_json_key_base64} 
    when:
      event: deployment
      environment: prod



