workspace:
  base: /workspace
  path: poc

pipeline:
  build_mrp_image:
    image: plugins/docker
    repo: harmeetg/mrp
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    secrets: [ docker_username, docker_password ]
    dockerfile: mrp/dockerfile
    context: mrp
    tags: ${COMMIT}
    pull_image: false
    volumes:
      - /var/lib/docker:/var/lib/docker


  publish_mrp:
    image: docker
    commands:
      - docker stop cntr_mrp
      - docker run --rm --pull=true -d --name cntr_mrp 0.0.0.0:80:4000 -d docker.io/harmeetg/mrp:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      environment: dev

  publish_mrp_to_gcr:
    image: nytimes/drone-gke
    cluster: drone-demo
    zone: us-central1-a
    namespace: ${BRANCH}
    secrets: [ gcr_json_key_base64 ]
    token: ${GCR_JSON_KEY_BASE64}
    vars:
      image: docker.io/gharmeet/mrp:$${COMMIT}
      app: mrp
      env: prod
    when:
      event: deployment
      environment: prod



