theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "aqua"
title: "My Reverse Phone"
description: "An amazing place for reverse phone lookup"
#url: http://138.68.230.87
layout: splash 
permalink: /:categories/:title
#header:
#  image: /assets/images/image-1.jpeg

author:
  name:  ""

defaults:
  # _pages
  - scope:
      path: ""
      type: pages 
    values:
      layout: splash 
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash 
      author_profile: true
      related: true
