FROM docker.io/ruby
RUN mkdir -p /app
WORKDIR /app
RUN gem install bundler
ADD Gemfile /app
RUN bundle install
ADD index.html /app
RUN bundle exec jekyll build
ENTRYPOINT ["bundle", "exec", "jekyll", "serve", "--host=0.0.0.0"]
